[package]
name = "yaatal-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
yaatal-core = { path = "../yaatal-core" }
yaatal-audit = { path = "../yaatal-audit" }
yaatal-policy = { path = "../yaatal-policy" }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
urlencoding = "2"
