//! Raw FFI bindings generated by `bindgen` from the upstream C ABI header.
//!
//! When the `speech-core-sys` Cargo feature is enabled, the real bindings are
//! included from `OUT_DIR/speech_core_sys.rs` (generated at build time by
//! `build.rs` using `bindgen`).
//!
//! When the feature is absent (e.g., `cargo check --no-default-features`),
//! a minimal *mock* binding is provided so that the safe Rust facade in
//! `session.rs` still type-checks without requiring the C++ toolchain.
//! The mock is labelled clearly and must **not** be shipped as a real runtime.

// ---------------------------------------------------------------------------
// Real bindgen output (requires speech-core-sys feature + C++ toolchain)
// ---------------------------------------------------------------------------

// Suppress the naming warnings that come from C-style identifiers in the
// generated file (snake_case enums, all-upper variants, etc.).
// The bindings are placed in a private `ffi` submodule with allows, then
// glob-re-exported so callers can use `crate::sys::sc_pipeline_t` etc.
#[cfg(feature = "speech-core-sys")]
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    clippy::upper_case_acronyms,
    clippy::enum_variant_names
)]
mod ffi_generated {
    include!(concat!(env!("OUT_DIR"), "/speech_core_sys.rs"));
}

// Re-export all generated symbols at the `sys` crate level.
#[cfg(feature = "speech-core-sys")]
pub use ffi_generated::*;

// ---------------------------------------------------------------------------
// MOCK BINDING — last-resort fallback for `cargo check --no-default-features`
//
// WARNING: These are stub types only.  They have no real implementations.
// Never link against these in a production build.
// Enable `speech-core-sys` (or use the `models` feature) for the real ABI.
// ---------------------------------------------------------------------------

#[cfg(not(feature = "speech-core-sys"))]
#[allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    clippy::upper_case_acronyms,
    clippy::enum_variant_names
)]
pub mod mock {
    use std::os::raw::{c_char, c_float, c_void};

    // Opaque pipeline handle.
    #[derive(Debug, Clone, Copy)]
    pub enum sc_pipeline_s {}
    pub type sc_pipeline_t = *mut sc_pipeline_s;

    // Enums
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum sc_mode_t {
        SC_MODE_PIPELINE = 0,
        SC_MODE_TRANSCRIBE_ONLY = 1,
        SC_MODE_ECHO = 2,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum sc_state_t {
        SC_STATE_IDLE = 0,
        SC_STATE_LISTENING = 1,
        SC_STATE_TRANSCRIBING = 2,
        SC_STATE_THINKING = 3,
        SC_STATE_SPEAKING = 4,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum sc_event_type_t {
        SC_EVENT_SESSION_CREATED = 0,
        SC_EVENT_SPEECH_STARTED = 1,
        SC_EVENT_SPEECH_ENDED = 2,
        SC_EVENT_PARTIAL_TRANSCRIPTION = 3,
        SC_EVENT_TRANSCRIPTION_COMPLETED = 4,
        SC_EVENT_RESPONSE_CREATED = 5,
        SC_EVENT_RESPONSE_INTERRUPTED = 6,
        SC_EVENT_RESPONSE_AUDIO_DELTA = 7,
        SC_EVENT_RESPONSE_DONE = 8,
        SC_EVENT_TOOL_CALL_STARTED = 9,
        SC_EVENT_TOOL_CALL_COMPLETED = 10,
        SC_EVENT_ERROR = 11,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum sc_role_t {
        SC_ROLE_SYSTEM = 0,
        SC_ROLE_USER = 1,
        SC_ROLE_ASSISTANT = 2,
        SC_ROLE_TOOL = 3,
    }

    // Structs — layout must match the C header exactly when real bindings are used.
    #[derive(Debug, Clone, Copy, Default)]
    #[repr(C)]
    pub struct sc_event_t {
        pub type_: sc_event_type_t,
        pub text: *const c_char,
        pub audio_data: *const u8,
        pub audio_data_length: usize,
        pub start_time: c_float,
        pub end_time: c_float,
        pub confidence: c_float,
        pub stt_duration_ms: c_float,
        pub llm_duration_ms: c_float,
        pub tts_duration_ms: c_float,
    }

    impl Default for sc_event_type_t {
        fn default() -> Self {
            sc_event_type_t::SC_EVENT_SESSION_CREATED
        }
    }

    // Callback types.
    pub type sc_event_fn =
        Option<unsafe extern "C" fn(event: *const sc_event_t, context: *mut c_void)>;

    // Stub extern block — these functions are NEVER called in mock mode.
    // They exist only so that session.rs can reference the symbols during
    // type-checking without requiring a linked speech_core.a.
    //
    // At link time, these must be provided by the real library.  Any binary
    // that enables the mock (i.e., builds without speech-core-sys) will fail
    // to link if it actually calls these — which is the correct behaviour.
    extern "C" {
        pub fn sc_pipeline_destroy(pipeline: sc_pipeline_t);
        pub fn sc_pipeline_start(pipeline: sc_pipeline_t);
        pub fn sc_pipeline_stop(pipeline: sc_pipeline_t);
        pub fn sc_pipeline_push_audio(
            pipeline: sc_pipeline_t,
            samples: *const c_float,
            count: usize,
        );
        pub fn sc_pipeline_state(pipeline: sc_pipeline_t) -> sc_state_t;
        pub fn sc_pipeline_is_running(pipeline: sc_pipeline_t) -> bool;
        pub fn sc_pipeline_resume_listening(pipeline: sc_pipeline_t);
    }
}

// Re-export mock types at crate level when feature is absent, so session.rs
// can use `crate::sys::sc_pipeline_t` uniformly.
#[cfg(not(feature = "speech-core-sys"))]
pub use mock::*;
